### ISSUE TITLE
Error: private method `named' called for ["mysql"]:Array

### ISSUE THREAD

**Issue by cdzombak** [rafaelgarrido/homebrew-caveats#5]
When trying to use `brew caveats`, I now receive this error:

```
~$ brew caveats mysql
Error: private method `named' called for ["mysql"]:Array
/usr/local/bin/brew-caveats.rb:11:in `caveats'
/usr/local/bin/brew-caveats.rb:27:in `<top (required)>'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/usr/local/Homebrew/Library/Homebrew/utils.rb:82:in `require?'
/usr/local/Homebrew/Library/Homebrew/brew.rb:105:in `<main>'
```

Running commit https://github.com/rafaelgarrido/homebrew-caveats/commit/c64d53ca893cc6af8900405650785a3c5c5abf7a

On macOS 10.14.6.

**Comment by lubomben** [comment]
The same on macOS 10.15.3 on all commands:

```
~/Utils/Scripts % brew caveats mysql
Error: private method `named' called for ["mysql"]:Array
/usr/local/bin/brew-caveats.rb:11:in `caveats'
/usr/local/bin/brew-caveats.rb:27:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/usr/local/Homebrew/Library/Homebrew/utils.rb:82:in `require?'
/usr/local/Homebrew/Library/Homebrew/brew.rb:105:in `<main>'
~/Utils/Scripts % brew caveats docker
Error: private method `named' called for ["docker"]:Array
/usr/local/bin/brew-caveats.rb:11:in `caveats'
/usr/local/bin/brew-caveats.rb:27:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/usr/local/Homebrew/Library/Homebrew/utils.rb:82:in `require?'
/usr/local/Homebrew/Library/Homebrew/brew.rb:105:in `<main>'
```

Running version: rafaelgarrido/caveats/brew-caveats 0.0.8

**Comment by cdzombak** [comment]
I think the fix ought to be straightforward, based on https://github.com/Homebrew/homebrew-linux-dev/pull/137/files#diff-5065860fe093585ceaa23b52a1552f08R46 , but I haven't had a chance to try it myself.

**Comment by rafaelgarrido** [comment]
@cdzombak @savonarola27 sorry for taking so long... hectic week here...

I just pushed a fix! @cdzombak you were right, the args object changed and I had to update the args parser... thank you for the hint...

Stay safe!

**Comment by cdzombak** [comment]
@rafaelgarrido no worries! Thank you for taking a look. I've confirmed the latest version now works on my machine.

> Stay safe!

You too!

**Comment by lubomben** [comment]
works also for me! thanks!
