### ISSUE TITLE
Warning: Calling Homebrew.args is deprecated!

### ISSUE THREAD

**Issue by lubomben** [rafaelgarrido/homebrew-caveats#6]
Hi, for some time now the command has always returned the following error for all brew commands:

```
~ % brew caveats xz
Warning: Calling Homebrew.args is deprecated! Use `args = <command>_args.parse` and pass `args` along the call chain instead.
```

I can't tell you exactly when it starts to present.

However the it still works:

```
~ % brew caveats curl
Warning: Calling Homebrew.args is deprecated! Use `args = <command>_args.parse` and pass `args` along the call chain instead.
==> curl: Caveats
curl is keg-only, which means it was not symlinked into /usr/local,
because macOS already provides this software and installing another version in
parallel can cause all kinds of trouble.

If you need to have curl first in your PATH run:
  echo 'export PATH="/usr/local/opt/curl/bin:$PATH"' >> ~/.zshrc

For compilers to find curl you may need to set:
  export LDFLAGS="-L/usr/local/opt/curl/lib"
  export CPPFLAGS="-I/usr/local/opt/curl/include"

For pkg-config to find curl you may need to set:
  export PKG_CONFIG_PATH="/usr/local/opt/curl/lib/pkgconfig"


zsh completions have been installed to:
  /usr/local/opt/curl/share/zsh/site-functions

fish completions have been installed to:
  /usr/local/opt/curl/share/fish/vendor_completions.d
```

Instead for casks it presents an error (always also in this case):

```
~ % brew cask caveats teamviewer
Error: undefined local variable or method `description' for Cask::Cmd::Caveats:Class
Please report this issue:
  https://docs.brew.sh/Troubleshooting
/usr/local/Homebrew/Library/Homebrew/cask/cmd/abstract_command.rb:36:in `parser'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/abstract_command.rb:92:in `initialize'
/usr/local/Homebrew/Library/Taps/rafaelgarrido/homebrew-caveats/cmd/brewcask-caveats.rb:11:in `initialize'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/abstract_command.rb:86:in `new'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/abstract_command.rb:86:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:233:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:218:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:150:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:14:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:112:in `<main>'
```

**Comment by rafaelgarrido** [comment]
Hello @savonarola27 ! Thank you for the heads up and sorry for taking so long to fix this. I didn't notice these warnings... Once you upgrade the tap your system should be fine with formulaes and casks. Thanks again and stay safe!
